# Generated by Django 5.0.3 on 2024-03-28 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_follow_follower_alter_follow_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follower',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('user', 'following')},
        ),
    ]
