# Generated by Django 5.0.3 on 2024-03-28 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_rename_follower_follow_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='user',
            new_name='follower',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='following',
            new_name='profile',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'profile')},
        ),
    ]
